### PR TITLE
Daisy/getActivity

### PR DESCRIPTION
**Pull request by HongxiChen1014**
- [x] add getActivityById API -> test ok
- [x] add table:tag, requirement, location

### CODE REVIEW

**Review by lisabuilds — COMMENTED** [review]
hi daisy, can we use datatype long for startTime and endTime since long is used for such values in the production ? let me know your thoughts 😊

**Review by lisabuilds — COMMENTED** [review]
ActivityService, is the UUID.randomUUID() from java.util generates the same uuid version as it's from uuid extension in postsql, please keep me posted on this issue : ) also i think alternative is to save activity instance without uuid attached, then db will generate uuid by default.

**Comment by HongxiChen1014** [comment]
> hi daisy, can we use datatype long for startTime and endTime since long is used for such values in the production ? let me know your thoughts 😊

Hi lisa, since jpa cannot convert long to timestamp, when running, there is error: bad type for long exsists.  
For jpa, if we use Timestamp in sql, in java we also use Timestamp. Let me know if you have any further questions~

**Comment by lisabuilds** [comment]
> > hi daisy, can we use datatype long for startTime and endTime since long is used for such values in the production ? let me know your thoughts 😊
> 
> Hi lisa, since jpa cannot convert long to timestamp, when running, there is error: bad type for long exsists. For jpa, if we use Timestamp in sql, in java we also use Timestamp. Let me know if you have any further questions~

👍

**Comment by HongxiChen1014** [comment]
> ActivityService, is the UUID.randomUUID() from java.util generates the same uuid version as it's from uuid extension in postsql, please keep me posted on this issue : ) also i think alternative is to save activity instance without uuid attached, then db will generate uuid by default.

sorry for that I forgot to delete this line. That is for test only before. I will delete this.

**Comment by lisabuilds** [comment]
> > ActivityService, is the UUID.randomUUID() from java.util generates the same uuid version as it's from uuid extension in postsql, please keep me posted on this issue : ) also i think alternative is to save activity instance without uuid attached, then db will generate uuid by default.
> 
> sorry for that I forgot to delete this line. That is for test only before. I already delete this generator.

**Review by lisabuilds — APPROVED** [review]

**Pull request merged**
